const { Octokit } = require("octokit");

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN,
});

const createPullRequestForRemediation = async ({
  alert,
  remediation,
}) => {
  const owner = process.env.GITHUB_OWNER;
  const repo = process.env.GITHUB_REPO;
  const base = process.env.GITHUB_BASE_BRANCH || "main";

  const branchName = `aura/fix-${alert._id}-${Date.now()}`;
  const filePath = `remediations/${alert.resourceName}-${alert.issueType}.tf`;

  const branchData = await octokit.rest.repos.getBranch({
    owner,
    repo,
    branch: base,
  });

  const baseSha = branchData.data.commit.sha;

  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });

  const contentEncoded = Buffer.from(remediation.generatedCode).toString("base64");

  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: filePath,
    message: `Aura remediation for ${alert.resourceName} (${alert.issueType})`,
    content: contentEncoded,
    branch: branchName,
  });

  const pullRequest = await octokit.rest.pulls.create({
    owner,
    repo,
    title: `Aura Remediation: ${alert.resourceName} - ${alert.issueType}`,
    head: branchName,
    base,
    body: [
      `This pull request was automatically generated by Aura.`,
      ``,
      `**Alert ID:** ${alert._id}`,
      `**Resource:** ${alert.resourceName}`,
      `**Issue Type:** ${alert.issueType}`,
      `**Severity:** ${alert.severity}`,
      ``,
      `**Explanation:**`,
      remediation.explanation,
    ].join("\n"),
  });

  return {
    branchName,
    filePath,
    prUrl: pullRequest.data.html_url,
    prNumber: pullRequest.data.number,
  };
};

module.exports = {
  createPullRequestForRemediation,
};